### ISSUE TITLE
The package repository settings are boken

### ISSUE THREAD

**Issue by usagi** [media-io/xml-schema#6]
Fix these package settings, please. These URLs are `404 NOT FOUND` now. In minutes ago, I was need find and identification the repos from old URL. 🤣 

- xml_schema/Cargo.toml
    - package.repository -> https://github.com/media-io/xml-schema/blob/805f323a76eb15135fcfac07e5874db49daf9ea1/xml_schema/Cargo.toml#L9
    - package.homepage -> https://github.com/media-io/xml-schema/blob/805f323a76eb15135fcfac07e5874db49daf9ea1/xml_schema/Cargo.toml#L10
- xml_schema/xml_schema_derive/Cargo.toml
    - https://github.com/media-io/xml-schema/blob/805f323a76eb15135fcfac07e5874db49daf9ea1/xml_schema_derive/Cargo.toml#L9
    - https://github.com/media-io/xml-schema/blob/805f323a76eb15135fcfac07e5874db49daf9ea1/xml_schema_derive/Cargo.toml#L10

![image](https://user-images.githubusercontent.com/115972/89969379-32de0080-dc91-11ea-9859-ec28174c7630.png)

---
It's easy to fix, but I don't know what you want to set it correctly such as repos top or workspace dirs or README files. Thus, I would not PR.

**Comment by MarcAntoine-Arnaud** [comment]
Done ! Thank you very much for this report.
